version: '3'

services:
  build:
    image: node:14
    volumes:
      - .:/app
    working_dir: '/app'
    command: 'npm start'

  web:
    image: nginx:1.19
    ports:
      - 8080:80
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf